<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Faulthistory_FB" Id="{87c5bab5-d17b-4290-8430-adbee1119843}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Faulthistory_FB EXTENDS FB_Cell
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>