<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Motor_FB" Id="{9b3ada02-ffd2-4e0a-9396-9cd5f8ad298b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Motor_FB
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Delay" Id="{eb52c425-d85a-487e-94c7-f839f48eecf7}">
      <Declaration><![CDATA[METHOD M_Delay : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Start" Id="{d1c8712d-a0e9-45aa-915c-8b3841d464bd}">
      <Declaration><![CDATA[METHOD PUBLIC M_Start : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Stop" Id="{3e665fa6-4a1d-4c20-82c6-daca24e7ff33}">
      <Declaration><![CDATA[METHOD M_Stop : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>